sudo: false
language: rust

# tarpaulin has only been tested on bionic and trusty other distros may have issues
dist: bionic
addons:
  apt:
    packages:
      - libssl-dev

cache: cargo
rust:
  - nightly
  - beta
  - stable
  # and the first stable one (this should be bumped as the minimum
  # Rust version required changes)
  - "1.36"

before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - |
      if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        cargo install cargo-tarpaulin
      fi

script:
- cargo fmt -- --check
- cargo clippy
- cargo build
- cargo test
- cargo bench

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi

after_failure:
  - tree -h

env:
  global:
    - RUST_BACKTRACE=1
